In [1]:
import boto3
import pandas as pd

session = boto3.Session(profile_name='AdministratorAccess-794038242332')

s3 = session.client('s3')

In [2]:
# Parâmetros do download
bucket_name = 'desafio-sprint5'  
s3_key = 'uploads/dadosogu.csv' 
local_file_path = 'C:/Users/sidci/OneDrive/Documentos/Bruna/compass/sprint5/dadosogu_baixado.csv'

try:
    s3.download_file(Bucket=bucket_name, Key=s3_key, Filename=local_file_path)
    print("Arquivo baixado com sucesso!")
except Exception as e:
    print("Erro ao baixar o arquivo:", e)

Arquivo baixado com sucesso!

In [3]:
dadosgov = pd.read_csv('dadosogu_baixado.csv', sep='|', dtype={19: object})

In [4]:
dadosgov

,data_referencia,cod_ibge,txt_nome_municipio,txt_sigla_uf,txt_regiao,dt_assinatura,cod_operacao,txt_nome_empreendimento,txt_nome_agente_financeiro,txt_modalidade,...,qtd_uh,qtd_uh_entregues,qtd_uh_vigentes,qtd_uh_distratadas,val_contratado_total,val_desembolsado,txt_cnpj_construtora_entidade,txt_nome_construtora_entidade,txt_endereco,txt_cep
0,30/09/2024,110.02,Porto Velho,RO,Norte,09/04/2010,29925581.0,RESIDENCIAL CIDADE DE TODOS III,CAIXA,FAR,...,240.0,240.0,0.0,0,13.830.963,"13.809.147,96",3.445271e+13,COMERCIO ENGENHARIA LTDA,"AV AMAZONAS, N� 9680 - BAIRRO SOCIALISTA",76800000.0
1,30/09/2024,110.02,Porto Velho,RO,Norte,09/04/2010,30011639.0,RESIDENCIAL CIDADE DE TODOS IX,CAIXA,FAR,...,240.0,240.0,0.0,0,14.218.052,"14.218.051,93",3.445271e+13,COMERCIO ENGENHARIA LTDA,"RUA OSWALDO RIBEIRO, S/N - SOCIALISTA",76800000.0
2,30/09/2024,110.02,Porto Velho,RO,Norte,09/07/2010,32680414.0,RESIDENCIAL CIDADE DE TODOS - LOTE 01,CAIXA,FAR,...,114.0,114.0,0.0,0,6.840.691,"6.840.691,6",2.364225e+12,CONSTRUTORA JOAO DE BARRO LTDA,AV AMAZONAS - LOTE 738,76800000.0
3,30/09/2024,110.02,Porto Velho,RO,Norte,09/07/2010,32703630.0,RESIDENCIAL CIDADE DE TODOS - LOTE 02,CAIXA,FAR,...,82.0,82.0,0.0,0,3.421.062,"3.421.062,22",2.364225e+12,CONSTRUTORA JOAO DE BARRO LTDA,"RUA MANE GARRICHA, LOTE 393",76800000.0
4,30/09/2024,110.02,Porto Velho,RO,Norte,25/06/2013,40267126.0,RESIDENCIAL PORTO BELLO II,CAIXA,FAR,...,272.0,272.0,0.0,0,18.161.056,"18.161.056,68",7.757862e+13,CASAALTA CONSTRUCOES E EMPREENDIMENTO LTDA.,"RUA DE ACESSO,(ATUAL JOSE FAID), S/N BAIRRO JD...",76800000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58341,30/09/2024,311.06,Cambuí,MG,Sudeste,27/04/2018,49099583.0,PNHR CAMBUI,CAIXA,Rural,...,7.0,0.0,0.0,7,256.900,38.535,NaN,NaN,NaN,NaN
58342,30/09/2024,260.41,Caruaru,PE,Nordeste,02/07/2024,63191186.0,RESIDENCIAL NOVA BARAUNA I ...,CAIXA,FAR,...,240.0,0.0,240.0,0,40.260.000,0,NaN,NaN,NaN,NaN
58343,30/09/2024,231.29,Sobral,CE,Nordeste,02/08/2024,63241600.0,RESIDENCIAL JARDINS DA SERRA II ...,CAIXA,FAR,...,192.0,0.0,192.0,0,"30.559.649,53",0,NaN,NaN,NaN,NaN
58344,30/09/2024,431.49,Porto Alegre,RS,Sul,27/09/2013,53367100.0,CONDOMINIO JARDIM DAS FIGUEIRAS III - FASE II,CAIXA,Entidades,...,360.0,360.0,0.0,0,30.852.862,30.852.862,5.948440e+12,INSTITUTO DE PLANEJAMENTO E ESTUDO SOCIO-AMBIE...,NaN,NaN
58345,30/09/2024,280.74,Tobias Barreto,SE,Nordeste,06/08/2024,63217932.0,RESIDENCIAL AGRIPINO BERNARDO DOS SANTOS IV ...,CAIXA,FAR,...,100.0,0.0,100.0,0,13.000.000,0,NaN,NaN,NaN,NaN

In [5]:
dadosgov.shape

(58346, 21)

In [6]:
dadosgov = dadosgov.drop_duplicates() ##apagar duplicadas

In [7]:
dadosgov.shape

(18151, 21)

In [8]:
dadosgov.info()

<class 'pandas.core.frame.DataFrame'>
Index: 18151 entries, 0 to 58345
Data columns (total 21 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   data_referencia                18151 non-null  object
 1   cod_ibge                       18151 non-null  float64
 2   txt_nome_municipio             18151 non-null  object
 3   txt_sigla_uf                   18151 non-null  object
 4   txt_regiao                     18137 non-null  object
 5   dt_assinatura                  18151 non-null  object
 6   cod_operacao                   13585 non-null  float64
 7   txt_nome_empreendimento        18151 non-null  object
 8   txt_nome_agente_financeiro     18151 non-null  object
 9   txt_modalidade                 18151 non-null  object
 10  txt_situacao_empreendimento    18151 non-null  object
 11  qtd_uh                         18151 non-null  float64
 12  qtd_uh_entregues               18150 non-null  float64
 13  qtd_uh_vigentes                18151 non-null  float64
 14  qtd_uh_distratadas             18151 non-null  int64
 15  val_contratado_total           18151 non-null  object
 16  val_desembolsado               18150 non-null  object
 17  txt_cnpj_construtora_entidade  13417 non-null  float64
 18  txt_nome_construtora_entidade  13426 non-null  object
 19  txt_endereco                   4067 non-null   object
 20  txt_cep                        4067 non-null   float64
dtypes: float64(7), int64(1), object(13)
memory usage: 3.0+ MB

In [9]:
dadosgov.nunique ()

data_referencia                      1
cod_ibge                          4610
txt_nome_municipio                4414
txt_sigla_uf                        27
txt_regiao                           5
dt_assinatura                     1785
cod_operacao                     13583
txt_nome_empreendimento          15649
txt_nome_agente_financeiro          25
txt_modalidade                       4
txt_situacao_empreendimento          3
qtd_uh                             730
qtd_uh_entregues                   713
qtd_uh_vigentes                    228
qtd_uh_distratadas                  69
val_contratado_total              6952
val_desembolsado                  6586
txt_cnpj_construtora_entidade     2953
txt_nome_construtora_entidade     2943
txt_endereco                      3524
txt_cep                           1747
dtype: int64

In [10]:
dadosgov.isnull().sum()

data_referencia                      0
cod_ibge                             0
txt_nome_municipio                   0
txt_sigla_uf                         0
txt_regiao                          14
dt_assinatura                        0
cod_operacao                      4566
txt_nome_empreendimento              0
txt_nome_agente_financeiro           0
txt_modalidade                       0
txt_situacao_empreendimento          0
qtd_uh                               0
qtd_uh_entregues                     1
qtd_uh_vigentes                      0
qtd_uh_distratadas                   0
val_contratado_total                 0
val_desembolsado                     1
txt_cnpj_construtora_entidade     4734
txt_nome_construtora_entidade     4725
txt_endereco                     14084
txt_cep                          14084
dtype: int64

In [11]:
dadosgov[dadosgov.txt_regiao.isnull()]

,data_referencia,cod_ibge,txt_nome_municipio,txt_sigla_uf,txt_regiao,dt_assinatura,cod_operacao,txt_nome_empreendimento,txt_nome_agente_financeiro,txt_modalidade,...,qtd_uh,qtd_uh_entregues,qtd_uh_vigentes,qtd_uh_distratadas,val_contratado_total,val_desembolsado,txt_cnpj_construtora_entidade,txt_nome_construtora_entidade,txt_endereco,txt_cep
58188,30/09/2024,270.630,PALMEIRA DOS INDIOS,AL,NaN,17/07/2024,62769362.0,RESIDENCIAL JULIA JOSEFA DE JESUS ...,CAIXA,FAR,...,150.0,0.0,150.0,0,21.450.000,0,NaN,NaN,NaN,NaN
58193,30/09/2024,291.080,FEIRA DE SANTANA,BA,NaN,11/07/2024,62678003.0,RESIDENCIAL RIO DE JANEIRO II ...,CAIXA,FAR,...,226.0,0.0,226.0,0,34.679.700,0,NaN,NaN,NaN,NaN
58213,30/09/2024,270.630,PALMEIRA DOS INDIOS,AL,NaN,17/07/2024,62769476.0,RESIDENCIAL PREFEITO GILENO COSTA SAMPAIO ...,CAIXA,FAR,...,100.0,0.0,100.0,0,14.300.000,0,NaN,NaN,NaN,NaN
58215,30/09/2024,210.900,PORTO FRANCO,MA,NaN,29/07/2024,63144086.0,JARDIM PORTO FRANCO II ...,CAIXA,FAR,...,50.0,0.0,50.0,0,"7.149.414,71",0,NaN,NaN,NaN,NaN
58216,30/09/2024,330.630,VOLTA REDONDA,RJ,NaN,04/07/2024,62768232.0,RESIDENCIAL THEREZINHA GONCALVES ...,CAIXA,FAR,...,112.0,0.0,112.0,0,17.877.000,0,NaN,NaN,NaN,NaN
58233,30/09/2024,353.080,MOGI MIRIM,SP,NaN,26/07/2024,63396684.0,CONJUNTO HABITACIONAL MANERA ...,CAIXA,FAR,...,100.0,0.0,100.0,0,"16.865.286,51",0,NaN,NaN,NaN,NaN
58274,30/09/2024,172.100,PALMAS,TO,NaN,02/07/2024,63107453.0,CONDOMINIO RESIDENCIAL PARQUE DOS IPES III ...,CAIXA,FAR,...,128.0,0.0,128.0,0,21.472.000,0,NaN,NaN,NaN,NaN
58278,30/09/2024,353.390,OLIMPIA,SP,NaN,05/07/2024,63239773.0,RESIDENCIAL OLIMPIA F ...,CAIXA,FAR,...,150.0,0.0,150.0,0,"23.455.901,48",0,NaN,NaN,NaN,NaN
58289,30/09/2024,250.750,JOAO PESSOA,PB,NaN,02/07/2024,61507208.0,RESIDENCIAL DO S ...,CAIXA,FAR,...,192.0,0.0,192.0,0,"32.570.144,96",0,NaN,NaN,NaN,NaN
58296,30/09/2024,291.005,DIAS DAVILA,BA,NaN,19/07/2024,63091057.0,RESIDENCIAL VILA CONCORDIA I ...,CAIXA,FAR,...,148.0,0.0,148.0,0,21.830.000,0,NaN,NaN,NaN,NaN
58308,30/09/2024,353.730,PENAPOLIS,SP,NaN,02/08/2024,62914563.0,RESIDENCIAL MUNDO NOVO IV ...,CAIXA,FAR,...,96.0,0.0,96.0,0,"15.489.564,14",0,NaN,NaN,NaN,NaN
58312,30/09/2024,270.630,PALMEIRA DOS INDIOS,AL,NaN,17/07/2024,62769258.0,RESIDENCIAL EURIDES NASCIMENTO TAVARES ...,CAIXA,FAR,...,150.0,0.0,150.0,0,21.450.000,0,NaN,NaN,NaN,NaN
58330,30/09/2024,290.570,CAMACARI,BA,NaN,19/07/2024,62743758.0,VERDES HORIZONTES I ...,CAIXA,FAR,...,192.0,0.0,192.0,0,32.524.800,0,NaN,NaN,NaN,NaN
58332,30/09/2024,290.570,CAMACARI,BA,NaN,19/07/2024,62743976.0,VERDES HORIZONTES II ...,CAIXA,FAR,...,192.0,0.0,192.0,0,32.524.800,0,NaN,NaN,NaN,NaN

In [12]:
estado_para_regiao = {
    'AC': 'Norte', 'AL': 'Nordeste', 'AP': 'Norte', 'AM': 'Norte',
    'BA': 'Nordeste', 'CE': 'Nordeste', 'DF': 'Centro-Oeste', 'ES': 'Sudeste',
    'GO': 'Centro-Oeste', 'MA': 'Nordeste', 'MT': 'Centro-Oeste', 'MS': 'Centro-Oeste',
    'MG': 'Sudeste', 'PA': 'Norte', 'PB': 'Nordeste', 'PR': 'Sul',
    'PE': 'Nordeste', 'PI': 'Nordeste', 'RJ': 'Sudeste', 'RN': 'Nordeste',
    'RS': 'Sul', 'RO': 'Norte', 'RR': 'Norte', 'SC': 'Sul',
    'SP': 'Sudeste', 'SE': 'Nordeste', 'TO': 'Norte'
}
dadosgov.loc[dadosgov['txt_regiao'].isna(), 'txt_regiao'] = dadosgov['txt_sigla_uf'].map(estado_para_regiao)

In [13]:
dadosgov[dadosgov.txt_regiao.isnull()]

Empty DataFrame
Columns: [data_referencia, cod_ibge, txt_nome_municipio, txt_sigla_uf, txt_regiao, dt_assinatura, cod_operacao, txt_nome_empreendimento, txt_nome_agente_financeiro, txt_modalidade, txt_situacao_empreendimento, qtd_uh, qtd_uh_entregues, qtd_uh_vigentes, qtd_uh_distratadas, val_contratado_total, val_desembolsado, txt_cnpj_construtora_entidade, txt_nome_construtora_entidade, txt_endereco, txt_cep]
Index: []

[0 rows x 21 columns]

In [14]:
dadosgov[dadosgov.val_desembolsado.isnull()]

,data_referencia,cod_ibge,txt_nome_municipio,txt_sigla_uf,txt_regiao,dt_assinatura,cod_operacao,txt_nome_empreendimento,txt_nome_agente_financeiro,txt_modalidade,...,qtd_uh,qtd_uh_entregues,qtd_uh_vigentes,qtd_uh_distratadas,val_contratado_total,val_desembolsado,txt_cnpj_construtora_entidade,txt_nome_construtora_entidade,txt_endereco,txt_cep
16193,30/09/2024,110.07,Campo Novo de Rondônia,RO,Norte,30/06/2016,1747317.0,1627-ALTAMIRA-12-RO,BB,Rural,...,4.0,0.0,4.0,0,126.000,NaN,5.888813e+12,ENTIDADE AUTARQUICA DE ASSIST TECN E EXTE RURA...,NaN,NaN

In [15]:
dadosgov.loc[dadosgov['val_desembolsado'].isna(), 'val_desembolsado'] = 0

In [16]:
dadosgov[dadosgov.val_desembolsado.isnull()]

Empty DataFrame
Columns: [data_referencia, cod_ibge, txt_nome_municipio, txt_sigla_uf, txt_regiao, dt_assinatura, cod_operacao, txt_nome_empreendimento, txt_nome_agente_financeiro, txt_modalidade, txt_situacao_empreendimento, qtd_uh, qtd_uh_entregues, qtd_uh_vigentes, qtd_uh_distratadas, val_contratado_total, val_desembolsado, txt_cnpj_construtora_entidade, txt_nome_construtora_entidade, txt_endereco, txt_cep]
Index: []

[0 rows x 21 columns]

In [17]:
dadosgov[dadosgov.qtd_uh_entregues.isnull()]

,data_referencia,cod_ibge,txt_nome_municipio,txt_sigla_uf,txt_regiao,dt_assinatura,cod_operacao,txt_nome_empreendimento,txt_nome_agente_financeiro,txt_modalidade,...,qtd_uh,qtd_uh_entregues,qtd_uh_vigentes,qtd_uh_distratadas,val_contratado_total,val_desembolsado,txt_cnpj_construtora_entidade,txt_nome_construtora_entidade,txt_endereco,txt_cep
19617,30/09/2024,355.03,São Paulo,SP,Sudeste,04/09/2015,45707347.0,COPA DO POVO GLEBA B,CAIXA,Entidades,...,648.0,NaN,648.0,0,15.205.558,0,7.367387e+12,ASS DE MORADORES DO ACAMPAMENTO ESPERANCA DE U...,RUA ISOSUKE OKAVE X RUA MALMEQUER DO CAMPO S/N...,8270700.0

In [18]:
dadosgov.loc[dadosgov.qtd_uh_entregues.isnull(), 'qtd_uh_entregues'] = 0.0

In [19]:
dadosgov[dadosgov.qtd_uh_entregues.isnull()]

Empty DataFrame
Columns: [data_referencia, cod_ibge, txt_nome_municipio, txt_sigla_uf, txt_regiao, dt_assinatura, cod_operacao, txt_nome_empreendimento, txt_nome_agente_financeiro, txt_modalidade, txt_situacao_empreendimento, qtd_uh, qtd_uh_entregues, qtd_uh_vigentes, qtd_uh_distratadas, val_contratado_total, val_desembolsado, txt_cnpj_construtora_entidade, txt_nome_construtora_entidade, txt_endereco, txt_cep]
Index: []

[0 rows x 21 columns]

In [20]:
dadosgov.info()

<class 'pandas.core.frame.DataFrame'>
Index: 18151 entries, 0 to 58345
Data columns (total 21 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   data_referencia                18151 non-null  object
 1   cod_ibge                       18151 non-null  float64
 2   txt_nome_municipio             18151 non-null  object
 3   txt_sigla_uf                   18151 non-null  object
 4   txt_regiao                     18151 non-null  object
 5   dt_assinatura                  18151 non-null  object
 6   cod_operacao                   13585 non-null  float64
 7   txt_nome_empreendimento        18151 non-null  object
 8   txt_nome_agente_financeiro     18151 non-null  object
 9   txt_modalidade                 18151 non-null  object
 10  txt_situacao_empreendimento    18151 non-null  object
 11  qtd_uh                         18151 non-null  float64
 12  qtd_uh_entregues               18151 non-null  float64
 13  qtd_uh_vigentes                18151 non-null  float64
 14  qtd_uh_distratadas             18151 non-null  int64
 15  val_contratado_total           18151 non-null  object
 16  val_desembolsado               18151 non-null  object
 17  txt_cnpj_construtora_entidade  13417 non-null  float64
 18  txt_nome_construtora_entidade  13426 non-null  object
 19  txt_endereco                   4067 non-null   object
 20  txt_cep                        4067 non-null   float64
dtypes: float64(7), int64(1), object(13)
memory usage: 3.6+ MB

In [21]:
dadosgov['data_referencia'].nunique()

1

In [22]:
colunas_remover = [
    'data_referencia',
    'txt_cnpj_construtora_entidade',
    'txt_nome_construtora_entidade',
    'txt_endereco',
    'txt_cep'
]
dadosgov = dadosgov.drop(columns=colunas_remover)

In [23]:
dadosgov.head(3)

,cod_ibge,txt_nome_municipio,txt_sigla_uf,txt_regiao,dt_assinatura,cod_operacao,txt_nome_empreendimento,txt_nome_agente_financeiro,txt_modalidade,txt_situacao_empreendimento,qtd_uh,qtd_uh_entregues,qtd_uh_vigentes,qtd_uh_distratadas,val_contratado_total,val_desembolsado
0,110.02,Porto Velho,RO,Norte,09/04/2010,29925581.0,RESIDENCIAL CIDADE DE TODOS III,CAIXA,FAR,Concluído,240.0,240.0,0.0,0,13.830.963,"13.809.147,96"
1,110.02,Porto Velho,RO,Norte,09/04/2010,30011639.0,RESIDENCIAL CIDADE DE TODOS IX,CAIXA,FAR,Concluído,240.0,240.0,0.0,0,14.218.052,"14.218.051,93"
2,110.02,Porto Velho,RO,Norte,09/07/2010,32680414.0,RESIDENCIAL CIDADE DE TODOS - LOTE 01,CAIXA,FAR,Concluído,114.0,114.0,0.0,0,6.840.691,"6.840.691,6"

In [24]:
dadosgov.info()

<class 'pandas.core.frame.DataFrame'>
Index: 18151 entries, 0 to 58345
Data columns (total 16 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   cod_ibge                     18151 non-null  float64
 1   txt_nome_municipio           18151 non-null  object
 2   txt_sigla_uf                 18151 non-null  object
 3   txt_regiao                   18151 non-null  object
 4   dt_assinatura                18151 non-null  object
 5   cod_operacao                 13585 non-null  float64
 6   txt_nome_empreendimento      18151 non-null  object
 7   txt_nome_agente_financeiro   18151 non-null  object
 8   txt_modalidade               18151 non-null  object
 9   txt_situacao_empreendimento  18151 non-null  object
 10  qtd_uh                       18151 non-null  float64
 11  qtd_uh_entregues             18151 non-null  float64
 12  qtd_uh_vigentes              18151 non-null  float64
 13  qtd_uh_distratadas           18151 non-null  int64
 14  val_contratado_total         18151 non-null  object
 15  val_desembolsado             18151 non-null  object
dtypes: float64(5), int64(1), object(10)
memory usage: 2.9+ MB

In [25]:
dadosgov

,cod_ibge,txt_nome_municipio,txt_sigla_uf,txt_regiao,dt_assinatura,cod_operacao,txt_nome_empreendimento,txt_nome_agente_financeiro,txt_modalidade,txt_situacao_empreendimento,qtd_uh,qtd_uh_entregues,qtd_uh_vigentes,qtd_uh_distratadas,val_contratado_total,val_desembolsado
0,110.02,Porto Velho,RO,Norte,09/04/2010,29925581.0,RESIDENCIAL CIDADE DE TODOS III,CAIXA,FAR,Concluído,240.0,240.0,0.0,0,13.830.963,"13.809.147,96"
1,110.02,Porto Velho,RO,Norte,09/04/2010,30011639.0,RESIDENCIAL CIDADE DE TODOS IX,CAIXA,FAR,Concluído,240.0,240.0,0.0,0,14.218.052,"14.218.051,93"
2,110.02,Porto Velho,RO,Norte,09/07/2010,32680414.0,RESIDENCIAL CIDADE DE TODOS - LOTE 01,CAIXA,FAR,Concluído,114.0,114.0,0.0,0,6.840.691,"6.840.691,6"
3,110.02,Porto Velho,RO,Norte,09/07/2010,32703630.0,RESIDENCIAL CIDADE DE TODOS - LOTE 02,CAIXA,FAR,Concluído,82.0,82.0,0.0,0,3.421.062,"3.421.062,22"
4,110.02,Porto Velho,RO,Norte,25/06/2013,40267126.0,RESIDENCIAL PORTO BELLO II,CAIXA,FAR,Concluído,272.0,272.0,0.0,0,18.161.056,"18.161.056,68"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58341,311.06,Cambuí,MG,Sudeste,27/04/2018,49099583.0,PNHR CAMBUI,CAIXA,Rural,Distratado/Cancelado,7.0,0.0,0.0,7,256.900,38.535
58342,260.41,Caruaru,PE,Nordeste,02/07/2024,63191186.0,RESIDENCIAL NOVA BARAUNA I ...,CAIXA,FAR,Não Concluído,240.0,0.0,240.0,0,40.260.000,0
58343,231.29,Sobral,CE,Nordeste,02/08/2024,63241600.0,RESIDENCIAL JARDINS DA SERRA II ...,CAIXA,FAR,Não Concluído,192.0,0.0,192.0,0,"30.559.649,53",0
58344,431.49,Porto Alegre,RS,Sul,27/09/2013,53367100.0,CONDOMINIO JARDIM DAS FIGUEIRAS III - FASE II,CAIXA,Entidades,Concluído,360.0,360.0,0.0,0,30.852.862,30.852.862
58345,280.74,Tobias Barreto,SE,Nordeste,06/08/2024,63217932.0,RESIDENCIAL AGRIPINO BERNARDO DOS SANTOS IV ...,CAIXA,FAR,Não Concluído,100.0,0.0,100.0,0,13.000.000,0

In [26]:
dadosgov.info()

<class 'pandas.core.frame.DataFrame'>
Index: 18151 entries, 0 to 58345
Data columns (total 16 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   cod_ibge                     18151 non-null  float64
 1   txt_nome_municipio           18151 non-null  object
 2   txt_sigla_uf                 18151 non-null  object
 3   txt_regiao                   18151 non-null  object
 4   dt_assinatura                18151 non-null  object
 5   cod_operacao                 13585 non-null  float64
 6   txt_nome_empreendimento      18151 non-null  object
 7   txt_nome_agente_financeiro   18151 non-null  object
 8   txt_modalidade               18151 non-null  object
 9   txt_situacao_empreendimento  18151 non-null  object
 10  qtd_uh                       18151 non-null  float64
 11  qtd_uh_entregues             18151 non-null  float64
 12  qtd_uh_vigentes              18151 non-null  float64
 13  qtd_uh_distratadas           18151 non-null  int64
 14  val_contratado_total         18151 non-null  object
 15  val_desembolsado             18151 non-null  object
dtypes: float64(5), int64(1), object(10)
memory usage: 2.9+ MB

In [27]:
dadosgov['qtd_uh'] = dadosgov['qtd_uh'].astype(int)

In [28]:
dadosgov['qtd_uh_vigentes'] = dadosgov['qtd_uh_vigentes'].astype(int)

In [29]:
dadosgov['qtd_uh_entregues'] = dadosgov['qtd_uh_entregues'].astype(float).astype(int)

In [30]:
dadosgov['val_desembolsado'] = (dadosgov['val_desembolsado']
    .str.replace('.', '', regex=False) 
    .str.replace(',', '.', regex=False)  
    .astype(float))

In [31]:
dadosgov['val_contratado_total'] = (
    dadosgov['val_contratado_total']
    .str.replace('.', '', regex=False) 
    .str.replace(',', '.', regex=False)  
    .astype(float))

In [32]:
dadosgov.info()

<class 'pandas.core.frame.DataFrame'>
Index: 18151 entries, 0 to 58345
Data columns (total 16 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   cod_ibge                     18151 non-null  float64
 1   txt_nome_municipio           18151 non-null  object
 2   txt_sigla_uf                 18151 non-null  object
 3   txt_regiao                   18151 non-null  object
 4   dt_assinatura                18151 non-null  object
 5   cod_operacao                 13585 non-null  float64
 6   txt_nome_empreendimento      18151 non-null  object
 7   txt_nome_agente_financeiro   18151 non-null  object
 8   txt_modalidade               18151 non-null  object
 9   txt_situacao_empreendimento  18151 non-null  object
 10  qtd_uh                       18151 non-null  int32
 11  qtd_uh_entregues             18151 non-null  int32
 12  qtd_uh_vigentes              18151 non-null  int32
 13  qtd_uh_distratadas           18151 non-null  int64
 14  val_contratado_total         18151 non-null  float64
 15  val_desembolsado             18150 non-null  float64
dtypes: float64(4), int32(3), int64(1), object(8)
memory usage: 2.7+ MB

In [33]:
dadosgov.to_csv('dadosok.csv')

In [34]:
bucket_name = 'desafio-sprint5'
file_path = "C:\\Users\\sidci\\OneDrive\\Documentos\\Bruna\\compass\\sprint5\\dadosok.csv"
s3_key = 'uploads/dadosogutratado.csv'

try:
    s3.upload_file(Filename=file_path, Bucket=bucket_name, Key=s3_key)
    print("Arquivo enviado com sucesso para o S3!")
except Exception as e:
    print("Erro ao enviar o arquivo:", e)

Arquivo enviado com sucesso para o S3!

A partir desse ponto começo a analise dos dados!

In [35]:
bucket_name = 'desafio-sprint5'  
s3_key = 'uploads/dadosogutratado.csv' 
local_file_path = 'C:/Users/sidci/OneDrive/Documentos/Bruna/compass/dadosok.csv'

try:
    s3.download_file(Bucket=bucket_name, Key=s3_key, Filename=local_file_path)
    print("Arquivo baixado com sucesso!")
except Exception as e:
    print("Erro ao baixar o arquivo:", e)

Arquivo baixado com sucesso!

A pergunta a ser respondida nessa analise é: No ano de 2018, quais foram as 10 cidades da região SUL, que mais tiveram imóveis concluídos e entregues subsidiados pela OGU , por intermedio de bancos públicos?

In [36]:
dadosanalise = pd.read_csv ('dadosok.csv')

In [37]:
dadosanalise

,Unnamed: 0,cod_ibge,txt_nome_municipio,txt_sigla_uf,txt_regiao,dt_assinatura,cod_operacao,txt_nome_empreendimento,txt_nome_agente_financeiro,txt_modalidade,txt_situacao_empreendimento,qtd_uh,qtd_uh_entregues,qtd_uh_vigentes,qtd_uh_distratadas,val_contratado_total,val_desembolsado
0,0,110.02,Porto Velho,RO,Norte,09/04/2010,29925581.0,RESIDENCIAL CIDADE DE TODOS III,CAIXA,FAR,Concluído,240,240,0,0,13830963.00,13809147.96
1,1,110.02,Porto Velho,RO,Norte,09/04/2010,30011639.0,RESIDENCIAL CIDADE DE TODOS IX,CAIXA,FAR,Concluído,240,240,0,0,14218052.00,14218051.93
2,2,110.02,Porto Velho,RO,Norte,09/07/2010,32680414.0,RESIDENCIAL CIDADE DE TODOS - LOTE 01,CAIXA,FAR,Concluído,114,114,0,0,6840691.00,6840691.60
3,3,110.02,Porto Velho,RO,Norte,09/07/2010,32703630.0,RESIDENCIAL CIDADE DE TODOS - LOTE 02,CAIXA,FAR,Concluído,82,82,0,0,3421062.00,3421062.22
4,4,110.02,Porto Velho,RO,Norte,25/06/2013,40267126.0,RESIDENCIAL PORTO BELLO II,CAIXA,FAR,Concluído,272,272,0,0,18161056.00,18161056.68
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18146,58341,311.06,Cambuí,MG,Sudeste,27/04/2018,49099583.0,PNHR CAMBUI,CAIXA,Rural,Distratado/Cancelado,7,0,0,7,256900.00,38535.00
18147,58342,260.41,Caruaru,PE,Nordeste,02/07/2024,63191186.0,RESIDENCIAL NOVA BARAUNA I ...,CAIXA,FAR,Não Concluído,240,0,240,0,40260000.00,0.00
18148,58343,231.29,Sobral,CE,Nordeste,02/08/2024,63241600.0,RESIDENCIAL JARDINS DA SERRA II ...,CAIXA,FAR,Não Concluído,192,0,192,0,30559649.53,0.00
18149,58344,431.49,Porto Alegre,RS,Sul,27/09/2013,53367100.0,CONDOMINIO JARDIM DAS FIGUEIRAS III - FASE II,CAIXA,Entidades,Concluído,360,360,0,0,30852862.00,30852862.00
18150,58345,280.74,Tobias Barreto,SE,Nordeste,06/08/2024,63217932.0,RESIDENCIAL AGRIPINO BERNARDO DOS SANTOS IV ...,CAIXA,FAR,Não Concluído,100,0,100,0,13000000.00,0.00

In [38]:
dadosanalise.info ()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18151 entries, 0 to 18150
Data columns (total 17 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Unnamed: 0                   18151 non-null  int64
 1   cod_ibge                     18151 non-null  float64
 2   txt_nome_municipio           18151 non-null  object
 3   txt_sigla_uf                 18151 non-null  object
 4   txt_regiao                   18151 non-null  object
 5   dt_assinatura                18151 non-null  object
 6   cod_operacao                 13585 non-null  float64
 7   txt_nome_empreendimento      18151 non-null  object
 8   txt_nome_agente_financeiro   18151 non-null  object
 9   txt_modalidade               18151 non-null  object
 10  txt_situacao_empreendimento  18151 non-null  object
 11  qtd_uh                       18151 non-null  int64
 12  qtd_uh_entregues             18151 non-null  int64
 13  qtd_uh_vigentes              18151 non-null  int64
 14  qtd_uh_distratadas           18151 non-null  int64
 15  val_contratado_total         18151 non-null  float64
 16  val_desembolsado             18150 non-null  float64
dtypes: float64(4), int64(5), object(8)
memory usage: 2.4+ MB

Uma função de conversão (convertendo o campo dt_assinatura para formato datetime)

In [39]:
dadosanalise['dt_assinatura'] = pd.to_datetime(dadosanalise['dt_assinatura'], format='%d/%m/%Y')

In [40]:
dadosanalise.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18151 entries, 0 to 18150
Data columns (total 17 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Unnamed: 0                   18151 non-null  int64
 1   cod_ibge                     18151 non-null  float64
 2   txt_nome_municipio           18151 non-null  object
 3   txt_sigla_uf                 18151 non-null  object
 4   txt_regiao                   18151 non-null  object
 5   dt_assinatura                18151 non-null  datetime64[ns]
 6   cod_operacao                 13585 non-null  float64
 7   txt_nome_empreendimento      18151 non-null  object
 8   txt_nome_agente_financeiro   18151 non-null  object
 9   txt_modalidade               18151 non-null  object
 10  txt_situacao_empreendimento  18151 non-null  object
 11  qtd_uh                       18151 non-null  int64
 12  qtd_uh_entregues             18151 non-null  int64
 13  qtd_uh_vigentes              18151 non-null  int64
 14  qtd_uh_distratadas           18151 non-null  int64
 15  val_contratado_total         18151 non-null  float64
 16  val_desembolsado             18150 non-null  float64
dtypes: datetime64[ns](1), float64(4), int64(5), object(7)
memory usage: 2.4+ MB

Uma função de String (convertendo para Maiusculas o campo txt_nome_municipio, txt_regiao, txt_nome_agente_financeiro)

In [41]:
dadosanalise[['txt_nome_municipio', 'txt_regiao', 'txt_nome_agente_financeiro']] = \
dadosanalise[['txt_nome_municipio', 'txt_regiao', 'txt_nome_agente_financeiro']].apply(lambda col: col.str.upper())

In [42]:
dadosanalise

,Unnamed: 0,cod_ibge,txt_nome_municipio,txt_sigla_uf,txt_regiao,dt_assinatura,cod_operacao,txt_nome_empreendimento,txt_nome_agente_financeiro,txt_modalidade,txt_situacao_empreendimento,qtd_uh,qtd_uh_entregues,qtd_uh_vigentes,qtd_uh_distratadas,val_contratado_total,val_desembolsado
0,0,110.02,PORTO VELHO,RO,NORTE,2010-04-09,29925581.0,RESIDENCIAL CIDADE DE TODOS III,CAIXA,FAR,Concluído,240,240,0,0,13830963.00,13809147.96
1,1,110.02,PORTO VELHO,RO,NORTE,2010-04-09,30011639.0,RESIDENCIAL CIDADE DE TODOS IX,CAIXA,FAR,Concluído,240,240,0,0,14218052.00,14218051.93
2,2,110.02,PORTO VELHO,RO,NORTE,2010-07-09,32680414.0,RESIDENCIAL CIDADE DE TODOS - LOTE 01,CAIXA,FAR,Concluído,114,114,0,0,6840691.00,6840691.60
3,3,110.02,PORTO VELHO,RO,NORTE,2010-07-09,32703630.0,RESIDENCIAL CIDADE DE TODOS - LOTE 02,CAIXA,FAR,Concluído,82,82,0,0,3421062.00,3421062.22
4,4,110.02,PORTO VELHO,RO,NORTE,2013-06-25,40267126.0,RESIDENCIAL PORTO BELLO II,CAIXA,FAR,Concluído,272,272,0,0,18161056.00,18161056.68
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18146,58341,311.06,CAMBUÍ,MG,SUDESTE,2018-04-27,49099583.0,PNHR CAMBUI,CAIXA,Rural,Distratado/Cancelado,7,0,0,7,256900.00,38535.00
18147,58342,260.41,CARUARU,PE,NORDESTE,2024-07-02,63191186.0,RESIDENCIAL NOVA BARAUNA I ...,CAIXA,FAR,Não Concluído,240,0,240,0,40260000.00,0.00
18148,58343,231.29,SOBRAL,CE,NORDESTE,2024-08-02,63241600.0,RESIDENCIAL JARDINS DA SERRA II ...,CAIXA,FAR,Não Concluído,192,0,192,0,30559649.53,0.00
18149,58344,431.49,PORTO ALEGRE,RS,SUL,2013-09-27,53367100.0,CONDOMINIO JARDIM DAS FIGUEIRAS III - FASE II,CAIXA,Entidades,Concluído,360,360,0,0,30852862.00,30852862.00
18150,58345,280.74,TOBIAS BARRETO,SE,NORDESTE,2024-08-06,63217932.0,RESIDENCIAL AGRIPINO BERNARDO DOS SANTOS IV ...,CAIXA,FAR,Não Concluído,100,0,100,0,13000000.00,0.00

Função de data isolando apenas o ano de 2018

In [43]:
dadosanalise['ano_assinatura'] = dadosanalise['dt_assinatura'].dt.year
df_2018 = dadosanalise[dadosanalise['ano_assinatura'] == 2018]

In [44]:
df_2018

,Unnamed: 0,cod_ibge,txt_nome_municipio,txt_sigla_uf,txt_regiao,dt_assinatura,cod_operacao,txt_nome_empreendimento,txt_nome_agente_financeiro,txt_modalidade,txt_situacao_empreendimento,qtd_uh,qtd_uh_entregues,qtd_uh_vigentes,qtd_uh_distratadas,val_contratado_total,val_desembolsado,ano_assinatura
22,22,220.700,OEIRAS,PI,NORDESTE,2018-07-30,50506923.0,ALTO DAS CANELA II,CAIXA,FAR,Concluído,12,12,0,0,780000.0,780000.00,2018
51,51,160.030,MACAPÁ,AP,NORTE,2018-02-07,49473844.0,VILA OPERARIOS,CAIXA,FAR,Não Concluído,224,0,224,0,21504000.0,11849809.19,2018
52,52,160.030,MACAPÁ,AP,NORTE,2018-06-07,49560352.0,VILA OPERARIOS,CAIXA,FAR,Não Concluído,276,0,276,0,26496000.0,13849511.13,2018
83,83,130.260,MANAUS,AM,NORTE,2018-01-30,48934594.0,RESIDENCIAL CIDADAO MANAUARA II - A,CAIXA,FAR,Concluído,500,500,0,0,41438189.0,41438189.09,2018
84,84,130.260,MANAUS,AM,NORTE,2018-10-11,48936212.0,RESIDENCIAL CIDADAO MANAUARA II - B,CAIXA,FAR,Concluído,500,500,0,0,41000000.0,41000000.00,2018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17985,58180,250.750,JOÃO PESSOA,PB,NORDESTE,2018-11-21,39010030.0,CONDOMINIO RES. CANAA II,BB,FAR,Concluído,480,480,0,0,41923965.0,37045920.00,2018
17986,58181,412.385,SANTA MARIA DO OESTE,PR,SUL,2018-04-27,48811713.0,CAPRICHANDO A MORADA STA M D OESTE,CAIXA,Rural,Distratado/Cancelado,11,0,0,11,555550.0,376200.00,2018
18051,58246,260.130,BARRA DE GUABIRABA,PE,NORDESTE,2018-04-27,49233754.0,BARRA DE GUABIRABA I,CAIXA,Rural,Distratado/Cancelado,16,0,0,16,547200.0,82080.00,2018
18060,58255,250.750,JOÃO PESSOA,PB,NORDESTE,2018-11-21,39010020.0,CONDOMINIO RES. CANAA I,BB,FAR,Concluído,480,480,0,0,41642308.0,36365064.00,2018
18146,58341,311.060,CAMBUÍ,MG,SUDESTE,2018-04-27,49099583.0,PNHR CAMBUI,CAIXA,Rural,Distratado/Cancelado,7,0,0,7,256900.0,38535.00,2018

Função de condicional para txt_situacao_do_empreendimento, por condicionando á "Concluído"

In [55]:
df_2018.loc[:,'concluido'] = df_2018['txt_situacao_empreendimento'].apply(lambda x: True if x == 'Concluído' else False)
df_concluidos = df_2018[df_2018['concluido']]

In [56]:
df_concluidos

,Unnamed: 0,cod_ibge,txt_nome_municipio,txt_sigla_uf,txt_regiao,dt_assinatura,cod_operacao,txt_nome_empreendimento,txt_nome_agente_financeiro,txt_modalidade,txt_situacao_empreendimento,qtd_uh,qtd_uh_entregues,qtd_uh_vigentes,qtd_uh_distratadas,val_contratado_total,val_desembolsado,ano_assinatura,concluido
22,22,220.700,OEIRAS,PI,NORDESTE,2018-07-30,50506923.0,ALTO DAS CANELA II,CAIXA,FAR,Concluído,12,12,0,0,780000.0,780000.00,2018,True
83,83,130.260,MANAUS,AM,NORTE,2018-01-30,48934594.0,RESIDENCIAL CIDADAO MANAUARA II - A,CAIXA,FAR,Concluído,500,500,0,0,41438189.0,41438189.09,2018,True
84,84,130.260,MANAUS,AM,NORTE,2018-10-11,48936212.0,RESIDENCIAL CIDADAO MANAUARA II - B,CAIXA,FAR,Concluído,500,500,0,0,41000000.0,41000000.00,2018,True
112,112,150.140,BELÉM,PA,NORTE,2018-07-17,49320696.0,RESIDENCIAL VIVER MARACACUERA II,CAIXA,FAR,Concluído,480,480,0,0,40130762.0,40130761.52,2018,True
113,113,150.140,BELÉM,PA,NORTE,2018-07-17,49322299.0,RESIDENCIAL VIVER MARACACUERA I,CAIXA,FAR,Concluído,480,480,0,0,39791897.0,39791897.78,2018,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13394,29442,420.517,ENTRE RIOS,SC,SUL,2018-04-27,48680163.0,PNHR ENTRE RIOS,CAIXA,Rural,Concluído,12,12,0,0,582672.0,410400.00,2018,True
13395,29443,420.517,ENTRE RIOS,SC,SUL,2018-04-27,48671957.0,PNHR ENTRE RIOS,CAIXA,Rural,Concluído,16,16,0,0,776896.0,547200.00,2018,True
13396,29444,420.517,ENTRE RIOS,SC,SUL,2018-04-27,48679697.0,PNHR ENTRE RIOS 17 UH,CAIXA,Rural,Concluído,17,17,0,0,825452.0,581400.00,2018,True
17985,58180,250.750,JOÃO PESSOA,PB,NORDESTE,2018-11-21,39010030.0,CONDOMINIO RES. CANAA II,BB,FAR,Concluído,480,480,0,0,41923965.0,37045920.00,2018,True
18060,58255,250.750,JOÃO PESSOA,PB,NORDESTE,2018-11-21,39010020.0,CONDOMINIO RES. CANAA I,BB,FAR,Concluído,480,480,0,0,41642308.0,36365064.00,2018,True

filtro de dados, com dois operadores lógicos, para bancos públicos (BB e CAIXA) e região SUL

In [47]:
filtrologico = ((df_concluidos['txt_nome_agente_financeiro'] == 'CAIXA') | 
                (df_concluidos['txt_nome_agente_financeiro'] == 'BB')) & \
                (df_concluidos['txt_regiao'] == 'SUL')

In [48]:
df_filtrado = df_concluidos[filtrologico]

In [49]:
df_filtrado

,Unnamed: 0,cod_ibge,txt_nome_municipio,txt_sigla_uf,txt_regiao,dt_assinatura,cod_operacao,txt_nome_empreendimento,txt_nome_agente_financeiro,txt_modalidade,txt_situacao_empreendimento,qtd_uh,qtd_uh_entregues,qtd_uh_vigentes,qtd_uh_distratadas,val_contratado_total,val_desembolsado,ano_assinatura,concluido
2665,2665,410.420,CAMPO LARGO,PR,SUL,2018-02-07,48898858.0,CAMPO LARGO I. RESIDENCIAL,CAIXA,FAR,Concluído,416,416,0,0,34112000.0,34112000.00,2018,True
2692,2692,410.830,FOZ DO IGUAÇU,PR,SUL,2018-05-28,49226152.0,RESIDENCIAL ANGATUBA,CAIXA,FAR,Concluído,340,340,0,0,27200000.0,27200000.00,2018,True
2693,2693,410.830,FOZ DO IGUAÇU,PR,SUL,2018-11-13,51242914.0,CONDOMINIO BOICY,CAIXA,FAR,Concluído,288,288,0,0,23040000.0,23040000.00,2018,True
2694,2694,410.830,FOZ DO IGUAÇU,PR,SUL,2018-11-13,51243157.0,CONDOMINIO BOICY II,CAIXA,FAR,Concluído,288,288,0,0,23040000.0,23040000.00,2018,True
2715,2715,411.140,IVAÍ,PR,SUL,2018-02-07,49897396.0,LOTEAMENTO PALMITAL I,CAIXA,FAR,Concluído,47,47,0,0,3377562.0,3377562.12,2018,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13330,29378,411.910,PIÊN,PR,SUL,2018-04-27,48793711.0,AGRICULT GI: CONSTR - PNHR PIEN,CAIXA,Rural,Concluído,10,10,0,0,342000.0,342000.00,2018,True
13342,29390,410.420,CAMPO LARGO,PR,SUL,2018-04-27,48788714.0,MORADIAS RURAIS CAMPO L - QUILOMBOLA,CAIXA,Rural,Concluído,14,14,0,0,478800.0,478800.00,2018,True
13394,29442,420.517,ENTRE RIOS,SC,SUL,2018-04-27,48680163.0,PNHR ENTRE RIOS,CAIXA,Rural,Concluído,12,12,0,0,582672.0,410400.00,2018,True
13395,29443,420.517,ENTRE RIOS,SC,SUL,2018-04-27,48671957.0,PNHR ENTRE RIOS,CAIXA,Rural,Concluído,16,16,0,0,776896.0,547200.00,2018,True
13396,29444,420.517,ENTRE RIOS,SC,SUL,2018-04-27,48679697.0,PNHR ENTRE RIOS 17 UH,CAIXA,Rural,Concluído,17,17,0,0,825452.0,581400.00,2018,True

ao menos 2 funçoes de agregação (groupby e sum)

In [50]:
df_resultado = df_filtrado.groupby(['txt_nome_municipio']).agg({
    'qtd_uh_entregues': 'sum',            
    'val_desembolsado': 'sum',  
     'txt_sigla_uf': 'first',    
   }).sort_values('qtd_uh_entregues', ascending=False)

In [51]:
df_resultado.head(10)

                    qtd_uh_entregues  val_desembolsado txt_sigla_uf
txt_nome_municipio
FOZ DO IGUAÇU                    916       73280000.00           PR
SANTA CRUZ DO SUL                563       35871343.00           RS
CANOAS                           500       41000000.00           RS
CAMPO LARGO                      430       34590800.00           PR
NOVO HAMBURGO                    305       24990000.00           RS
CURITIBANOS                      300       21095446.61           SC
SANTA MARIANA                    283       19385354.29           PR
SÃO BENTO DO SUL                 244       18497723.68           SC
JAGUARIAÍVA                      200       14372689.99           PR
CARAMBEÍ                         154       12054408.20           PR

In [52]:
df_analise = df_resultado.head(10)

In [53]:
df_analise.to_csv('analisecidades.csv')

In [54]:
bucket_name = 'desafio-sprint5'
file_path = "C:\\Users\\sidci\\OneDrive\\Documentos\\Bruna\\compass\\sprint5\\analisecidades.csv"
s3_key = 'uploads/analisecidades.csv'

try:
    s3.upload_file(Filename=file_path, Bucket=bucket_name, Key=s3_key)
    print("Arquivo enviado com sucesso para o S3!")
except Exception as e:
    print("Erro ao enviar o arquivo:", e)

Arquivo enviado com sucesso para o S3!